apiVersion: apps/v1
kind: Deployment
metadata:
  name: commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commerce
  template:
    metadata:
      labels:
        app: commerce
    spec:
      containers:
      - name: commerce
        image: ignacioborraz/commerce:1.0.0
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: commerce-service
spec:
  selector:
    app: commerce
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
  type: LoadBalancer